# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "./spire",
    "./spire-*",
]

default-members = [
    "./spire",
    "./spire-*",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
readme = "./README.md"
license = "MIT"

authors = ["Oleh Martsokha <o.martsokha@gmail.com>"]
repository = "https://github.com/spire-rs/spire"
homepage = "https://github.com/spire-rs/spire"
documentation = "https://docs.rs/spire"

[workspace.dependencies]
spire = { path = "./spire", version = "0.1.0" }
spire-core = { path = "./spire-core", version = "0.1.0" }
spire-macros = { path = "./spire-macros", version = "0.1.0" }

tokio = { version = "1.36.0", default-features = false }
tower = { version = "0.4.13", default-features = false }

bytes = { version = "1.6.0" }
futures = { version = "0.3.30" }
async-trait = { version = "0.1.78" }
pin-project-lite = { version = "0.2.13" }
thiserror = { version = "1.0.58" }
serde = { version = "1.0.197" }
time = { version = "0.3.34" }
